# Generated by Django 2.0.5 on 2018-06-05 22:26

from django.db import migrations, models
import placeweb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to=placeweb.models.make_upload)),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('F', 'Finished')], default='Q', max_length=1)),
            ],
        ),
    ]
