# Generated by Django 2.0.5 on 2018-06-06 01:52

from django.db import migrations, models
import placeweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('placeweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='upload',
        ),
        migrations.AddField(
            model_name='experiment',
            name='config',
            field=models.FileField(default='', upload_to=placeweb.models.make_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='data',
            field=models.FileField(default='', upload_to=placeweb.models.make_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='metadata',
            field=models.FileField(default='', upload_to=placeweb.models.make_upload),
            preserve_default=False,
        ),
    ]
