name: place
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.1
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.1.4
  - matplotlib=3.8.0
  - django
  - pyserial=3.5
  - pyyaml=6.0.1
  - setuptools=68.2.2
  - pylint=2.16.2
  - dash=2.14.2
  - dash-bootstrap-components=1.5.0
