name: place
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - matplotlib
  - django
  - pyserial
  - pyyaml
  - setuptools
  - pylint
  - dash
  - dash-bootstrap-components
