package:
    name: place
    version: "{{ load_setup_py_data().version }}"

source:
    path: .

build:
    number: 1

requirements:
    build:
        - python
        - pyserial
        - pyyaml
        - setuptools
        - pylint

    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - django
        - pyserial
        - dash
        - dash-bootstrap-components

test:
    requires:
        - python
        - numpy
        - scipy
        - pandas
        - matplotlib
        - django
        - pyserial
        - pylint
        - dash
        - dash-bootstrap-components

about:
    home: https://github.com/PALab/place
    license: GPLv3
    license_file: LICENSE
