package:
    name: place
    version: "0.2.1a"

source:
    path: .

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - httplib2
        - obspy
        - numpy >=1.0.0
        - scipy
        - matplotlib
        - h5py
        - pyserial

test:
    requires:
        - httplib2
        - lxml

    imports:
        - place

about:
    home: https://github.com/PALab/place
    license: LGPLv3
    license_file: COPYING

