package: controller.py __init__.py parseConstants.py test_controller.py test_parseConstants.py utility.py exampleAverageMultipleRecords.py	exampleAcquireInstancesAfterCommand.py
	mkdir -p ${DIR}/osciCard
	cp controller.py __init__.py parseConstants.py test_controller.py test_parseConstants.py utility.py exampleAverageMultipleRecords.py	exampleAcquireInstancesAfterCommand.py ${DIR}/osciCard

